for ref_aln in mtmalign 3dcoffee 3dcoffee_TMalign; do
		for mode in sp tc; do
			for test_aln in psicoffee tcoffee famsa ginsi msaprobs 3dcoffee 3dcoffee_TMalign mtmalign; do
				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode"
				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".perc

        		t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln  -compare_mode "$mode" -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".avg
        		t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln  -compare_mode "$mode" -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".avg.perc				

				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln  -compare_mode "$mode" -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".pair
				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln  -compare_mode "$mode" -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".pair.perc				

				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".same_state
				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" | tr -d "]" > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".same_state.perc

        		t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".avg.same_state
        		t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".avg.same_state.perc

				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".pair.same_state
				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".pair.same_state.perc

				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".without_loops
				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" | tr -d "]" > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".without_loops.perc

        		t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".avg.without_loops
        		t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc

				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".pair.without_loops
				t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_"$test_aln".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_"$test_aln"_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc
			done
	
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode" > "!{fam}"_selected_ref_"$ref_aln"."$mode"
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".avg > "!{fam}"_selected_ref_"$ref_aln"."$mode".avg
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".pair > "!{fam}"_selected_ref_"$ref_aln"."$mode".pair

		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".perc > "!{fam}"_selected_ref_"$ref_aln"."$mode".perc
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".avg.perc > "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.perc
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".pair.perc > "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.perc


		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".same_state.perc > "!{fam}"_selected_ref_"$ref_aln"."$mode".same_state.perc
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".avg.same_state.perc > "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.same_state.perc
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".pair.same_state.perc > "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.same_state.perc	

		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".same_state > "!{fam}"_selected_ref_"$ref_aln"."$mode".same_state
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".avg.same_state > "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.same_state
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".pair.same_state > "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.same_state	



		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".without_loops > "!{fam}"_selected_ref_"$ref_aln"."$mode".without_loops
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".avg.without_loops > "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.without_loops
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".pair.without_loops > "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.without_loops			

		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".without_loops.perc > "!{fam}"_selected_ref_"$ref_aln"."$mode".without_loops.perc
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc > "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.without_loops.perc
		paste "!{fam}"_selected_ref_famsa_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_ginsi_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_msaprobs_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_tcoffee_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_psicoffee_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_3dcoffee_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_3dcoffee_TMalign_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_mtmalign_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc > "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.without_loops.perc			

		done			
done

for x in alphafold; do
	for ref_aln in mtmalign 3dcoffee 3dcoffee_TMalign; do
		for mode in sp tc; do
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode"
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".perc

			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.perc

			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.perc

			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode"
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".perc

			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.perc

			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.perc		
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode"
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".perc			
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.perc			
			
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode" "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode" > new_selected_"$ref_aln"."$mode"
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".perc > new_selected_"$ref_aln"."$mode".perc
			
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg > new_selected_"$ref_aln"."$mode".avg
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.perc > new_selected_"$ref_aln"."$mode".avg.perc
			
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair > new_selected_"$ref_aln"."$mode".pair
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.perc > new_selected_"$ref_aln"."$mode".pair.perc

			mv new_selected_"$ref_aln"."$mode" "!{fam}"_selected_ref_"$ref_aln"."$mode"
			mv new_selected_"$ref_aln"."$mode".perc "!{fam}"_selected_ref_"$ref_aln"."$mode".perc

            mv new_selected_"$ref_aln"."$mode".avg "!{fam}"_selected_ref_"$ref_aln"."$mode".avg
            mv new_selected_"$ref_aln"."$mode".avg.perc "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.perc
			
			mv new_selected_"$ref_aln"."$mode".pair "!{fam}"_selected_ref_"$ref_aln"."$mode".pair
			mv new_selected_"$ref_aln"."$mode".pair.perc "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.perc

			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".same_state
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".same_state.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".same_state
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".same_state.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".same_state
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".same_state.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]=[Struc]' -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state.perc
			
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".same_state > new_selected_"$ref_aln"."$mode".same_state
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".same_state.perc > new_selected_"$ref_aln"."$mode".same_state.perc

			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state > new_selected_"$ref_aln"."$mode".avg.same_state
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.same_state.perc > new_selected_"$ref_aln"."$mode".avg.same_state.perc

			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state > new_selected_"$ref_aln"."$mode".pair.same_state
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.same_state.perc > new_selected_"$ref_aln"."$mode".pair.same_state.perc

			mv new_selected_"$ref_aln"."$mode".same_state "!{fam}"_selected_ref_"$ref_aln"."$mode".same_state
			mv new_selected_"$ref_aln"."$mode".same_state.perc "!{fam}"_selected_ref_"$ref_aln"."$mode".same_state.perc

            mv new_selected_"$ref_aln"."$mode".avg.same_state "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.same_state
            mv new_selected_"$ref_aln"."$mode".avg.same_state.perc "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.same_state.perc

			mv new_selected_"$ref_aln"."$mode".pair.same_state "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.same_state
			mv new_selected_"$ref_aln"."$mode".pair.same_state.perc "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.same_state.perc

			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".without_loops
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".without_loops.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".without_loops
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".without_loops.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_3dcoffee_TMalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' | grep -v "seq1" | grep -v "*" | awk -v var=!{fam} '{print var"\t"$4}' ORS="\t" > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".without_loops
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' | grep -v "seq1" | grep -v "*" | tr -d '[]' | awk -v var=!{fam} '{print var"\t"$5}' ORS="\t" > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".without_loops.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format s | awk -v var=!{fam} '{print $1"\t"var"\t"$4}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format s | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"var"\t"$5}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc
			
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format p | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$4}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops
			t_coffee -other_pg aln_compare -al1 "!{fam}"_selected_ref_"$ref_aln".fa_aln -al2 "!{fam}"_selected_ref_mtmalign_"$x".fa_aln -compare_mode "$mode" -st !{dssp_fasta} pep -io_cat '[H][H]+[E][E]+[H][E]=[Struc]' -io_format p | tr -d '[]' | awk -v var=!{fam} '{print $1"\t"$2"\t"var"\t"$5}' > "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc
			
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".without_loops > new_selected_"$ref_aln"."$mode".without_loops
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".without_loops.perc > new_selected_"$ref_aln"."$mode".without_loops.perc

			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops > new_selected_"$ref_aln"."$mode".avg.without_loops
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".avg.without_loops.perc > new_selected_"$ref_aln"."$mode".avg.without_loops.perc

			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops > new_selected_"$ref_aln"."$mode".pair.without_loops
			paste "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_3dcoffee_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_3dcoffee_TMalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_mtmalign_"$x"_vs_ref_"$ref_aln"."$mode".pair.without_loops.perc > new_selected_"$ref_aln"."$mode".pair.without_loops.perc

			mv new_selected_"$ref_aln"."$mode".without_loops "!{fam}"_selected_ref_"$ref_aln"."$mode".without_loops
			mv new_selected_"$ref_aln"."$mode".without_loops.perc "!{fam}"_selected_ref_"$ref_aln"."$mode".without_loops.perc

            mv new_selected_"$ref_aln"."$mode".avg.without_loops "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.without_loops
            mv new_selected_"$ref_aln"."$mode".avg.without_loops.perc "!{fam}"_selected_ref_"$ref_aln"."$mode".avg.without_loops.perc

			mv new_selected_"$ref_aln"."$mode".pair.without_loops "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.without_loops
			mv new_selected_"$ref_aln"."$mode".pair.without_loops.perc "!{fam}"_selected_ref_"$ref_aln"."$mode".pair.without_loops.perc
		done
	done
done
